lib/mango_web/router.ex
defmodule MangoWeb.Router do
  use MangoWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :frontend do
    plug MangoWeb.Plugs.LoadCustomer
    plug MangoWeb.Plugs.FetchCart
  end

  scope "/", MangoWeb do
    pipe_through [:browser, :frontend]

    get "/", PageController, :index
    get "/categories/:name", CategoryController, :show
    get "/register", RegistrationController, :new
    post "/register", RegistrationController, :create
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/cart", CartController, :show
    post "/cart", CartController, :add
    put "/cart", CartController, :update
  end

  scope "/", MangoWeb do
    pipe_through [:browser, :frontend, MangoWeb.Plugs.AuthenticateCustomer]

    get "/checkout", CheckoutController, :edit
    get "/logout", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", MangoWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: MangoWeb.Telemetry
    end
  end
end

lib/mango_web/controllers/cart_controller.ex
defmodule MangoWeb.CartController do
  use MangoWeb, :controller
  alias Mango.Sales

  def show(conn, _) do
    cart = conn.assigns.cart
    cart_changeset = Sales.change_cart(cart)
    render(conn, "show.html", cart: cart, cart_changeset: cart_changeset)
  end

  def add(conn, %{"cart" => cart_params}) do
    cart = conn.assigns.cart

    case Sales.add_to_cart(cart, cart_params) do
      {:ok, cart} ->
        render(conn, "add.json", cart: cart, cart_params: cart_params)

      {:error, _} ->
        conn
        |> put_flash(:error, "Error adding product to cart")
        |> redirect(to: Routes.page_path(conn, :index))
    end
  end

  def update(conn, %{"order" => cart_params}) do
    cart = conn.assigns.cart

    case Sales.update_cart(cart, cart_params) do
      {:ok, _} ->
        conn
        |> put_flash(:info, "Cart updated successfully")
        |> redirect(to: Routes.cart_path(conn, :show))

      {:error, _} ->
        conn
        |> put_flash(:error, "Error updating cart")
        |> redirect(to: Routes.cart_path(conn, :show))
    end
  end
end

lib/mango_web/views/cart_view.ex
defmodule MangoWeb.CartView do
  use MangoWeb, :view
  alias Mango.Sales.Order

  def render("add.json", %{cart: cart, cart_params: cart_params}) do
    %{"product_name" => name, "pack_size" => size, "quantity" => qty} = cart_params

    %{
      message: "Product added to cart - #{name} (#{size}) x #{qty} qty",
      cart_count: cart_count(cart)
    }
  end

  def cart_count(conn = %Plug.Conn{}) do
    cart_count(conn.assigns.cart)
  end

  def cart_count(cart = %Order{}) do
    Enum.reduce(cart.line_items, 0, fn item, acc ->
      acc + item.quantity
    end)
  end

  def cart_link_text(conn) do
    raw("""
    <i class="fa fa-shopping-cart"></i> <span class="cart-count">#{cart_count(conn)}</span>
    """)
  end
end

lib/mango_web/templates/cart/show.html.eex
<div class="col-md-6 col-md-offset-3">
  <h1>Cart</h1>
  <%= if Enum.empty?(@cart.line_items) do %>
    <p>Your cart is empty</p>
  <% else %>
    <%= form_for @cart_changeset, "/cart", fn f -> %>
      <table class="table">
        <thead>
          <tr>
            <th>Product Name</th>
            <th>Pack Size</th>
            <th>Quantity</th>
            <th>Unit Price</th>
            <th>Subtotal</th>
            <th>Remove?</th>
          </tr>
        </thead>
        <tbody>
          <%= inputs_for f, :line_items, fn lf -> %>
            <tr>
              <td><%= lf.data.product_name %></td>
              <td><%= lf.data.pack_size %></td>
              <td>
                <%= hidden_input lf, :product_id %>
                <%= number_input lf, :quantity, class: "form-control cart-qty" %>
                <%= error_tag lf, :quantity %>
              </td>
              <td>MYR <%= lf.data.unit_price %></td>
              <td>MYR <%= lf.data.total %></td>
              <td><%= checkbox lf, :delete %></td>
            </tr>
          <% end %>
          <tr>
            <td colspan=4>Order Total</td>
            <td>MYR <%= @cart.total %></td>
          </tr>
        </tbody>
      </table>
      <div class="form-group">
        <%= submit "Update Cart", class: "btn btn-primary" %>
      </div>
      <%= link "Check Out", to: Routes.checkout_path(@conn, :edit), class: "btn btn-primary pull-right" %>
    <% end %>
  <% end %>
</div>